# w = tuple(int(line) for line in open('./files/01.txt'))
w = list(int(line) for line in open('./files/01.txt'))
print(w)
print(sorted(w))
w.sort(key=lambda e: (e%2, e))
print(w)
w.sort(key=lambda e: (e%2==0, e))
print(w)
w.sort(key=lambda e: len(str(e)))
print(w)
w.sort(key=lambda e: (len(str(e)), -e))
print(w)
print(filter(lambda e: e%2==0, w))
from functools import reduce
print(reduce(lambda a, b: a+b, w) / len(w))